name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DOTNET_VERSION: '10.0.x'
  BACKEND_PATH: './backend/src/Web'

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.BACKEND_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Check formatting
        run: |
          dotnet tool restore
          dotnet csharpier check ../..

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ../../tests --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
      
      - name: List TestResults
        run: ls -R ./TestResults || echo "No results found"
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: '**/TestResults/*.trx'
